Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recetas.Controllers
{
    public class PerfilController : Controller
    {
        // GET: Perfil
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RecetasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Recetas.Models;

namespace Recetas.Controllers
{
    public class RecetasController : Controller
    {
        private complexEntities db = new complexEntities();
        // GET: Recetas
        public ActionResult Index()
        {
            return View(db.Recetas.ToList());
        }

        public ActionResult Detail()
        {
            return View();
        }

        public ActionResult Detail_Receta(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receta receta = db.Recetas.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }
    }
}

Controllers/SuscripcionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recetas.Controllers
{
    public class SuscripcionController : Controller
    {
        // GET: Suscripcion
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Pago()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/4df0687f9f.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- logo -->
        <a class="navbar-brand" href="@Url.Action("Index","Perfil")">
            <div class="back-usuario" >
                <i class="fas fa-user usuario"></i>
            </div>
        </a>

        <!-- enlaces -->
        <div class="collapse navbar-collapse" id="opciones">
            <hr />
            <div class="container">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a style="font-size: 25px; color: black;" class="nav-link" href="@Url.Action("Index","Home")"> <i class="fas fa-home"></i> Página Principal</a>
                    </li>
                    <li class="nav-item">
                        <a style="font-size: 25px; color: black;" class="nav-link" href="@Url.Action("Index","Recetas")"> <i class="fas fa-book"></i> Todas las recetas</a>
                    </li>
                    <li class="nav-item">
                        <a style="font-size: 25px; color: black;" class="nav-link" href="@Url.Action("Index","Suscripcion")"> <i class="fas fa-dollar-sign"></i> Suscripción</a>
                    </li>
                </ul>
            </div>
            <hr />
        </div>
    </nav>

    <div>
        @RenderBody()


    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>